conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm
app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views.logout_user, name='logout'),

]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

puddle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('item/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your Username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your Username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

core/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import logout

from item.models import Category, Item

from .forms import SignupForm


def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()

    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items
    })


def contact(request):
    return render(request, 'core/contact.html')


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form': form
    })


def logout_user(request):
    logout(request)
    messages.success(request, 'You have been logged out.')
    return redirect('core:index')

core/templates/core/base.html
<!doctype html>

<html lang="">
    <head>
        {% load static %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"/>

        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon_io/apple-touch-icon.png' %}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon_io/favicon-32x32.png' %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon_io/favicon-16x16.png' %}">
        <link rel="manifest" href="{% static 'favicon_io/site.webmanifest' %}">

        <script src="https://cdn.tailwindcss.com"></script>
        <title>{% block title %} {% endblock %} | hakoNest</title>

    </head>

    <body>
        <nav class="py-6 px-6 flex justify-between items-center shadow-md">
            <a href="/" class="text-4xl font-semibold flex items-center">
                <img src="{% static 'favicon_io/apple-touch-icon.png' %}" alt="hakoNest logo" class="h-12 w-auto">
               <span class="px-2">hakoNest</span>
            </a>
            <div class="space-x-6">
                <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500">Add Property</a>
                <a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-gray-500">Find Your Place</a>

                {% if request.user.is_authenticated %}
                    <a href="{% url 'conversation:inbox' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
                    <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
                    <a href="{% url 'core:logout' %}" class="px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-700">Logout</a>
                {% else %}
                    <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign Up</a>
                    <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log In</a>
                {% endif %}
            </div>
        </nav>
        <div class="px-6 py-6">
            {% if messages %}
            	<div class="messages">
                    {% for message in messages %}
                    	<div class="alert alert-{{ message.tags }} text-red-400">{{ message }}</div>
                    {% endfor %}

                </div>
            {% endif %}
            {% block content %}
            {% endblock %}
        </div>

        <footer class="py-6 px-6 flex justify-between bg-gray-800" id="about">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-white text-2xl" >About</h3>
                <p class="text-lg text-white">
                    Welcome to hakoNest, your go-to platform for finding the perfect student accommodation.
                    Our mission is to simplify the process of finding rooms, apartments, and PG accommodations
                    for students. Whether you're a student looking for a comfortable place to stay or a landlord
                    wanting to list a property, hakoNest connects you directly, with no hidden fees or complications.
                </p><br>

                <p class="text-lg text-gray-500">
                            <a class="text-white hover:text-teal" href="#">&copy; hakoNest</a> 2024, All Right Reserved. Made By
                    <a class="text-white hover:text-white-700" href="https://raktimrabha.com">Raktim Rabha</a> and
                    <a class="text-white hover:text-white-700" href="#">Aman Magar</a>
                </p>
            </div>
             <div class="w1/3">
                    <h3 class="mb-5 font-semibold text-gray-400">Links</h3>

                    <ul class="space-y-2">
                        <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                        <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                        <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy Policy</a></li>
                        <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Term of Use </a></li>

                    </ul>

                </div>
        </footer>
    </body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
     <h1>The contact page</h1>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock %}
{% load static %}

{% block content %}
    <div class="bg-white">
          <div class="flex flex-col-reverse md:flex-row items-center">
              <!-- Text Section -->
              <div class="md:w-1/2 p-5 mt-10 md:mt-0 space-y-4">
                  <h1 class="text-4xl font-bold md:text-5xl mb-4">
                      Find your <span class="text-teal-500">perfect space</span> easy, affordable, and student-friendly
                  </h1>
                  <p class="text-lg text-gray-600 mb-4 pb-2">

                  </p>
                  
                  <div class="space-x-3">
                      <a href="{% url 'item:items' %}" class="btn bg-teal-500 text-white py-3 px-9 rounded-lg hover:bg-teal-600 transition duration-300">Find Now</a>
                      <a href="{% url 'core:signup' %}" class="btn bg-teal-500 text-white py-3 px-9 rounded-lg hover:bg-teal-600 transition duration-300">Sign Up</a>
                  </div>
              </div>
              <!-- Image Carousel Section-->
              <div class="md:w-1/2 swiper mySwiper">
                  <div class="relative swiper-wrapper">
                    <div class="swiper-slide">
                    <img src="{% static 'img/room_picture.jpg' %}" class="w-full h-auto rounded-lg shadow-md transition-opacity duration-700 opacity-100" alt="Room 1">
                    </div>
                    <div class="swiper-slide">
                          <img src="" class="w-full h-auto rounded-lg shadow-md transition-opacity duration-700 opacity-0" alt="Carousel Image 2">
                    </div>
{#                    <div class="swiper-button-next"></div>#}
{#                    <div class="swiper-button-prev"></div>#}
                  </div>
              </div>
          </div>
    </div>
     <div class="mt-6 px-6 py-12 p    bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Recently Added</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" class="rounded-t-xl object-cover" alt="{{ item.name }}">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500 text-xl">₹ {{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
     </div>

    <div class="mt-6 px-6 py-12 p    bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Room Types</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
                <div>
                    <a href="#">
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{category.name }}</h2>
                            <p class="text-gray-500">{{ category.items.count }}</p>
                        </div>
                    </a>
                </div>
            {% endfor%}
        </div>
    </div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log in</h1>

    <form method="post" action=".">
        {% csrf_token %}
        <div class="mb-3">
            <label class="inline-block mb-2" for="">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2" for="">Password</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Login</button>
    </form>
</div>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}
        <div class="mb-3">
            <label class="inline-block mb-2" for="">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2" for="">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2" for="">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2" for="">Repeat Password</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}